### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by schef** [thomasgeissl/QMidi#1]
Hello,
i tried to compile this package using qt5:
`qmake -project` which created QMidi.pro file.
edited QMidi.pro file by adding
`QT += gui core widgets`
and appending
`./libs/rtmidi/` to `INCLUDEPATH  += .` line.
When i run `make`
 i got output which i put to pastebin link.

http://pastebin.com/PPYf2ETg

**Comment by thomasgeissl** [comment]
Hello @schef,
I will have a look.

Did the provided example compile?
Which platform are you using? Linux?

Please note that this project is a work in progress and quite unstable at the moment. There are still some bugs which I have not had the time to fix. Do not hesitate to file issues on github.

Thomas

**Comment by schef** [comment]
Hi,
i'm on archlinux up-to-date.
Maybe i'm mission some dependencies but i cant figure out which ones.
I'm new to QT so i don't know much about it.

**Comment by thomasgeissl** [comment]
rtMidi should be the only dependency and it is included in this repo. I just compiled the example on Ubuntu. Have a look at the rtMidi project and check its dependencies.

It uses a dummy backend on your system, I guess you did not link against the rtMidi library or maybe you miss some dependencies.
The compiler also complains about multiple definitions.

Can you try if the following works for you?

``` sh
git clone https://github.com/thomasgeissl/QMidi.git
cd QMidi/examples/example
mkdir build && cd $_
qmake ../example.pro
make
```

**Comment by schef** [comment]
Yes this works..and i can send midi messages using `./example` program.

**Comment by thomasgeissl** [comment]
Nice. If you want to include QMidi in your own app, just include QMidi.pri as in the example and it should compile.

I am going to close this. Just open new issues if you encounter any problems.

**Comment by schef** [comment]
Ok thanks..!:)
