### ISSUE TITLE
Compile failure on windows

### ISSUE THREAD

**Issue by cdwijs** [thomasgeissl/QMidi#5]
I have opened example.pro, configure, and start debug. Then I get the following compile errors:
`
g++ -Wl,-subsystem,windows -mthreads -o debug\example.exe object_script.example.Debug  -lmingw32 -LC:\Qt\5.10.1\mingw53_32\lib C:\Qt\5.10.1\mingw53_32\lib\libqtmaind.a -LC:\utils\my_sql\my_sql\lib -LC:\utils\postgresql\pgsql\lib -lshell32 C:\Qt\5.10.1\mingw53_32\lib\libQt5Widgetsd.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Guid.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Cored.a 
./debug\RtMidi.o: In function `midiInputCallback':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:1984: undefined reference to `_imp__midiInAddBuffer@12'
./debug\RtMidi.o: In function `ZN11MidiInWinMM10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2035: undefined reference to `_imp__midiInGetNumDevs@0'
./debug\RtMidi.o: In function `ZN11MidiInWinMM8openPortEjNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2061: undefined reference to `_imp__midiInGetNumDevs@0'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2081: undefined reference to `_imp__midiInOpen@20'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2096: undefined reference to `_imp__midiInPrepareHeader@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2098: undefined reference to `_imp__midiInClose@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2105: undefined reference to `_imp__midiInAddBuffer@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2107: undefined reference to `_imp__midiInClose@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2114: undefined reference to `_imp__midiInStart@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2116: undefined reference to `_imp__midiInClose@4'
./debug\RtMidi.o: In function `ZN11MidiInWinMM9closePortEv':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2137: undefined reference to `_imp__midiInReset@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2138: undefined reference to `_imp__midiInStop@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2141: undefined reference to `_imp__midiInUnprepareHeader@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2145: undefined reference to `_imp__midiInClose@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2152: undefined reference to `_imp__midiInClose@4'
./debug\RtMidi.o: In function `ZN11MidiInWinMM12getPortCountEv':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2160: undefined reference to `_imp__midiInGetNumDevs@0'
./debug\RtMidi.o: In function `ZN11MidiInWinMM11getPortNameB5cxx11Ej':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2166: undefined reference to `_imp__midiInGetNumDevs@0'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2176: undefined reference to `_imp__midiInGetDevCapsW@12'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2221: undefined reference to `_imp__midiOutGetNumDevs@0'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM12getPortCountEv':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2234: undefined reference to `_imp__midiOutGetNumDevs@0'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM11getPortNameB5cxx11Ej':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2240: undefined reference to `_imp__midiOutGetNumDevs@0'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2250: undefined reference to `_imp__midiOutGetDevCapsW@12'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM8openPortEjNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2279: undefined reference to `_imp__midiOutGetNumDevs@0'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2299: undefined reference to `_imp__midiOutOpen@20'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM9closePortEv':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2313: undefined reference to `_imp__midiOutReset@4'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2314: undefined reference to `_imp__midiOutClose@4'
./debug\RtMidi.o: In function `ZN12MidiOutWinMM11sendMessageEPSt6vectorIhSaIhEE':
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2357: undefined reference to `_imp__midiOutPrepareHeader@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2366: undefined reference to `_imp__midiOutLongMsg@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2375: undefined reference to `_imp__midiOutUnprepareHeader@12'
C:\Users\crldewijs\Desktop\git\QMidi-ori\examples\build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug/../../libs/rtmidi/RtMidi.cpp:2396: undefined reference to `_imp__midiOutShortMsg@8'
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [debug\example.exe] Error 1
mingw32-make: *** [debug] Error 2

Makefile.Debug:107: recipe for target 'debug\example.exe' failed
mingw32-make[1]: Leaving directory 'C:/Users/crldewijs/Desktop/git/QMidi-ori/examples/build-example-Desktop_Qt_5_10_1_MinGW_32bit-Debug'
Makefile:36: recipe for target 'debug' failed
11:29:20: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project example (kit: Desktop Qt 5.10.1 MinGW 32bit)
When executing step "Make"
11:29:20: Elapsed time: 00:28.
`
I run windows 7, Qt 5.10.1, and mingw53_32.

**Comment by cdwijs** [comment]
The solution is to add the line "LIBS += -lwinmm" to QMidi.pri like his:
`
macx{
    DEFINES += __MACOSX_CORE__=1
    LIBS += -framework CoreMidi
    LIBS += -framework CoreAudio
    LIBS += -framework CoreFoundation
}

linux{
    DEFINES += define __LINUX_ALSA__=1
    LIBS += -lasound
}
win32{
    DEFINES += __WINDOWS_MM__=1
	LIBS += -lwinmm
}
INCLUDEPATH += $$PWD
INCLUDEPATH += $$PWD/libs/rtmidi


HEADERS += \
    $$PWD/libs/rtmidi/RtMidi.h \
    $$PWD/qmidiin.h \
    $$PWD/qmidiout.h \
    $$PWD/qmidimessage.h \
    $$PWD/qmidimapper.h \
    $$PWD/qmidipianoroll.h
SOURCES += \
    $$PWD/libs/rtmidi/RtMidi.cpp \
    $$PWD/qmidiin.cpp \
    $$PWD/qmidiout.cpp \
    $$PWD/qmidimessage.cpp \
    $$PWD/qmidimapper.cpp \
    $$PWD/qmidipianoroll.cpp

DISTFILES += \
    $$PWD/README.md
    $$PWD/LICENSE
`
https://stackoverflow.com/questions/18120080/llink-winmm-lib-to-qt-creator
Thanks,
Cedric

**Comment by cdwijs** [comment]
I have created a pull request with the fix here:
https://github.com/thomasgeissl/QMidi/pull/6

**Comment by thomasgeissl** [comment]
i was not able to test it, since i do not have a windows os available. if it works for you, feel free to close the issue. thanks
